config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  resources :products
  resources :products_grouping, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  amount     :float            default(0.0), not null
#  code       :string           not null
#  price      :float            not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ApplicationRecord
  validates_presence_of :price, :code, :amount
  validates_numericality_of :price, :amount
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :price, :amount)
    end
end

app/controllers/products_grouping_controller.rb
class ProductsGroupingController < ApplicationController
  def new
    @products_grouping = ProductsGrouping.new(products: products)
  end

  def create
    @products_grouping = ProductsGrouping.new(products_grouping_params)
    @products_grouping.products = products

    if @products_grouping.save
      redirect_to products_path, notice: 'Products Grouping was successfully created.'
    else
      render :new
    end
  end

  private
    def products
      Product.where(id: params[:selected_products])
    end

    def products_grouping_params
      params.require(:products_grouping).permit(:new_price, :new_code,
        :products, :extra_amount)
    end
  # private end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_grouping_helper.rb
module ProductsGroupingHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleStock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag new_products_grouping_path, method: :get do %>
  <h1>Products</h1>

  <table>
    <thead>
      <tr>
        <th></th>
        <th>Code</th>
        <th>Price</th>
        <th>Amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= check_box_tag("selected_products[]", product.id) %></td>
          <td><%= product.code %></td>
          <td><%= product.price %></td>
          <td><%= product.amount %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td>
            <%= link_to 'Destroy', product, method: :delete,
            data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag "Group Products" %>
<% end %>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @product.amount %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products_grouping/new.html.erb
<%= form_with(model: @products_grouping, local: true) do |f| %>
  <% if @products_grouping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@products_grouping.errors.count, "error") %>
      prohibited this from being saved:</h2>

      <ul>
      <% @products_grouping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>Products</h1>

  <table>
    <thead>
      <th>Code</th>
      <th>Price</th>
      <th>Amount</th>
    </thead>
    <tbody>
      <% @products_grouping.products.each do |product| %>
        <%= hidden_field_tag "selected_products[]", product.id %>
        <tr>
          <td><%= product.code %></td>
          <td><%= product.price %></td>
          <td><%= product.amount %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <th colspan="2">Total</th>
      <td><%= @products_grouping.products.map(&:amount).sum %></td>
    </tfoot>
  </table>

  <div class="field">
    <%= f.label :new_code %>
    <%= f.text_field :new_code %>
  </div>

  <div class="field">
    <%= f.label :new_price %>
    <%= f.text_field :new_price %>
  </div>

  <div class="field">
    <%= f.label :extra_amount %>
    <%= f.text_field :extra_amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', products_path %>